version: '3.3'
 
services:
  wordpress:
    build: .
    depends_on:
      - db
    ports:
      - "8000:80"
      - "3000:3000"
      - "3001:3001"      
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - .db/conf:/etc/mysql/conf.d
      - .db/sql:/docker-entrypoint-initdb.d
      - .db/data:/var/lib/mysql

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    depends_on:
      - db
    ports:
      - "8001:80"
    volumes:
      - ".db/phpmyadmin/sessions:/sessions"
      
  wordmove:
      tty: true
      depends_on:
          - wordpress
      image: welaika/wordmove
      restart: on-failure:5
      volumes:
          - ./config:/home/
          - ~/.ssh:/home/.ssh
      environment:
          LOCAL_SERVER_PORT: "${LOCAL_SERVER_PORT}"
          PRODUCTION_URL: "${PRODUCTION_URL}"
          PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
          PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
          PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
          PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
          PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
          PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
          PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
          PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
          PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT}" 
volumes:
    db_data:
